import { cleanSearch,pageRange,serviceCall } from "./apiClient";
export const applicationsService={
  list:async({search="",status="",jobId="",recruiterId="",sort="newest",page=1,pageSize=25}={})=>serviceCall(async db=>{const range=pageRange(page,pageSize);let q=db.from("applications").select("id,reference_number,job_title,status,rating,source,submitted_at,candidate_id,recruiter_id,candidates(full_name,cnic,phone,city,current_trade)",{count:"exact"}).order("submitted_at",{ascending:sort==="oldest"}).range(range.from,range.to);const term=cleanSearch(search);if(term)q=q.or(`reference_number.ilike.%${term}%,job_title.ilike.%${term}%`);if(status)q=q.eq("status",status);if(jobId)q=q.eq("job_id",jobId);if(recruiterId)q=q.eq("recruiter_id",recruiterId);return q},{context:"applications.list",fallback:"Unable to load applications."}),
  mine:async({page=1,pageSize=25}={})=>serviceCall(db=>{const range=pageRange(page,pageSize);return db.from("applications").select("id,reference_number,job_title,status,created_at,submitted_at,interview_date",{count:"exact"}).order("submitted_at",{ascending:false}).range(range.from,range.to)},{context:"applications.mine",fallback:"Unable to load your applications."}),
  track:async(reference,identifier)=>serviceCall(db=>db.rpc("track_application",{p_reference:reference.trim(),p_identifier:identifier.trim()}),{context:"applications.track",fallback:"No matching application was found."}),
  get:async id=>serviceCall(db=>db.from("applications").select("*,candidates(*),candidate_documents(*),candidate_notes(*),interviews(*),application_status_history(*)").eq("id",id).single(),{context:"applications.get",fallback:"Unable to load this application."}),
  updateStatus:async(id,status)=>serviceCall(db=>db.from("applications").update({status}).eq("id",id).select().single(),{context:"applications.status",fallback:"Unable to update the application status."}),
  assignRecruiter:async(id,recruiterId)=>serviceCall(db=>db.from("applications").update({recruiter_id:recruiterId}).eq("id",id).select().single(),{context:"applications.assign",fallback:"Unable to assign the recruiter."}),
  addNote:async payload=>serviceCall(db=>db.from("candidate_notes").insert({...payload,author_id:payload.author_id||payload.created_by}).select().single(),{context:"applications.note",fallback:"Unable to save the note."})
};
