import { useEffect,useRef,useState } from "react";
import { Link } from "react-router-dom";
import { offices } from "../data/siteData";

export function PageHero({eyebrow,title,text,image}){return <section className="page-hero" style={{"--page-image":`url(${image})`}}><div><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>}
export function SectionHeading({eyebrow,title,text,light=false}){return <div className={`section-heading reveal ${light?"light":""}`}><span>{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
export function CTA({title="Ready to build your workforce?",text="Speak with our recruitment team about your next manpower requirement.",to="/hire",label="Hire Manpower"}){return <section className="cta-banner"><div className="reveal"><span className="kicker">Partner with experience</span><h2>{title}</h2><p>{text}</p><Link className="button" to={to}>{label} <span>→</span></Link></div></section>}
export function Counter({end,suffix="",label}){const [value,setValue]=useState(0);const ref=useRef();useEffect(()=>{const node=ref.current;const ob=new IntersectionObserver(([e])=>{if(!e.isIntersecting)return;const start=performance.now();const tick=now=>{const p=Math.min((now-start)/1400,1);setValue(Math.floor(end*(1-Math.pow(1-p,3))));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);ob.disconnect()},{threshold:.4});ob.observe(node);return()=>ob.disconnect()},[end]);return <div className="stat" ref={ref}><strong>{value.toLocaleString()}{suffix}</strong><span>{label}</span></div>}
export function Stats(){return <section className="stats reveal"><Counter end={50} suffix="+" label="Years Experience"/><Counter end={150000} suffix="+" label="Workers Supplied"/><Counter end={22} suffix="+" label="Countries Served"/><div className="stat"><strong>ISO 9001</strong><span>Certified Quality</span></div></section>}
export function JobCard({job}){return <article className="job-card reveal"><div className="job-top"><span className="job-flag">{job.flag}</span><span className="job-status">Recruiting</span></div><h3>{job.title}</h3><p className="job-country">{job.country} · {job.industry}</p><dl><div><dt>Salary</dt><dd>{job.salary}</dd></div><div><dt>Experience</dt><dd>{job.experience}</dd></div><div><dt>Accommodation</dt><dd>{job.accommodation}</dd></div><div><dt>Food</dt><dd>{job.food}</dd></div></dl><Link className="button small" to="/jobs#apply">Apply Now →</Link></article>}
export function OfficeGrid(){return <div className="office-grid">{offices.map((office,i)=><article className={`office-card reveal ${i===0?"head-office":""}`} key={office.name}><div className="office-icon">⌂</div><span>{office.type}</span><h3>{office.name}</h3><address>{office.address}</address></article>)}</div>}
export function SocialSection(){const links=[["whatsapp","Join our WhatsApp Channel","https://whatsapp.com/channel/0029VaRHlCdDDmFOW66gnK1I"],["tiktok","Follow us on TikTok","https://www.tiktok.com/@transarabian?_r=1&_t=ZS-97zt9iSxYp8"],["instagram","Follow us on Instagram","https://www.instagram.com/trans_arabian?igsh=MXNkODY2N29vNWhycg=="],["facebook","Like us on Facebook","https://www.facebook.com/share/1KywZ12ccF/?mibextid=wwXIfr"]];return <section className="section connect-section shade"><SectionHeading eyebrow="Stay connected" title="Connect With Us" text="Follow our official channels for recruitment news and company updates."/><div className="social-grid">{links.map(([brand,label,url])=><a className={`social-button social-${brand} reveal`} href={url} target="_blank" rel="noreferrer" key={brand}><span>{brand==="whatsapp"?"☏":brand==="tiktok"?"♪":brand==="instagram"?"◎":"f"}</span><div><small>Official channel</small><strong>{label}</strong></div><b>↗</b></a>)}</div></section>}
export function EmployerForm(){const [sent,setSent]=useState(false);return <form className="enterprise-form reveal" onSubmit={e=>{e.preventDefault();if(e.currentTarget.checkValidity()){setSent(true);e.currentTarget.reset()}else e.currentTarget.reportValidity()}}><div className="form-title"><span>Employer enquiry</span><h3>Tell us what you need</h3></div><div className="form-grid">{[["Company name","company","text"],["Country","country","text"],["Contact person","contact","text"],["Work email","email","email"],["Required positions","positions","text"],["Estimated workers","workers","number"]].map(([label,name,type])=><label className="field" key={name}><span className="field-label">{label}</span><input type={type} name={name} min={type==="number"?1:undefined} required/></label>)}<label className="field"><span className="field-label">Requirement details</span><textarea required></textarea></label></div><button className="button" type="submit">Submit Requirement →</button>{sent&&<p className="form-success">✓ Requirement received. Our team will contact you shortly.</p>}</form>}
