import { lazy,Suspense,useEffect } from "react";
import { BrowserRouter,Route,Routes,useLocation } from "react-router-dom";
import Navbar from "./components/Navbar";import Footer from "./components/Footer";import ScrollManager from "./components/ScrollManager";import ProtectedRoute from "./components/auth/ProtectedRoute";import { AuthProvider } from "./context/AuthProvider";import "./App.css";
import { ROLES,STAFF_ROLES } from "./config/roles";
const Home=lazy(()=>import("./pages/Home")),About=lazy(()=>import("./pages/About")),Services=lazy(()=>import("./pages/Services")),Process=lazy(()=>import("./pages/Process")),Jobs=lazy(()=>import("./pages/Jobs")),JobDetailsPage=lazy(()=>import("./pages/JobDetails")),JobApplication=lazy(()=>import("./pages/JobApplication")),ApplicationConfirmation=lazy(()=>import("./pages/ApplicationConfirmation")),SavedJobs=lazy(()=>import("./pages/SavedJobs")),Hire=lazy(()=>import("./pages/Hire")),Facilities=lazy(()=>import("./pages/Facilities")),Gallery=lazy(()=>import("./pages/Gallery")),Contact=lazy(()=>import("./pages/Contact")),NotFound=lazy(()=>import("./pages/NotFound")),Account=lazy(()=>import("./pages/Account")),CandidateDashboard=lazy(()=>import("./pages/candidate/CandidateDashboard")),TrackApplication=lazy(()=>import("./pages/TrackApplication")),LegalPage=lazy(()=>import("./pages/LegalPage"));
const Login=lazy(()=>import("./pages/auth/Login")),CandidateLogin=lazy(()=>import("./pages/auth/CandidateLogin")),Register=lazy(()=>import("./pages/auth/Register")),ForgotPassword=lazy(()=>import("./pages/auth/ForgotPassword")),ResetPassword=lazy(()=>import("./pages/auth/ResetPassword")),Unauthorized=lazy(()=>import("./pages/auth/Unauthorized"));
const AdminLayout=lazy(()=>import("./components/admin/AdminLayout")),AdminDashboard=lazy(()=>import("./pages/admin/AdminDashboard")),AdminJobs=lazy(()=>import("./pages/admin/AdminJobs")),JobEditor=lazy(()=>import("./pages/admin/JobEditor")),AdminApplications=lazy(()=>import("./pages/admin/AdminApplications")),ApplicationReview=lazy(()=>import("./pages/admin/ApplicationReview")),AdminCandidates=lazy(()=>import("./pages/admin/AdminCandidates")),CandidateProfilePage=lazy(()=>import("./pages/admin/CandidateProfilePage")),AdminInterviews=lazy(()=>import("./pages/admin/AdminInterviews")),AdminReports=lazy(()=>import("./pages/admin/AdminReports")),AdminUsers=lazy(()=>import("./pages/admin/AdminUsers")),AdminSettings=lazy(()=>import("./pages/admin/AdminSettings"));
function AppLayout(){const location=useLocation();const admin=location.pathname.startsWith("/admin");useEffect(()=>{const move=e=>{document.documentElement.style.setProperty("--mouse-x",`${e.clientX}px`);document.documentElement.style.setProperty("--mouse-y",`${e.clientY}px`)};window.addEventListener("pointermove",move,{passive:true});return()=>window.removeEventListener("pointermove",move)},[]);return <div className="site"><ScrollManager/>{!admin&&<Navbar/>}<main key={location.pathname} className="page-transition"><Suspense fallback={<div className="page-loader"><span></span><p>Loading Trans Arabian</p></div>}><Routes>
  <Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/process" element={<Process/>}/><Route path="/jobs" element={<Jobs/>}/><Route path="/jobs/:slug" element={<JobDetailsPage/>}/><Route path="/jobs/:slug/apply" element={<JobApplication/>}/><Route path="/jobs/:slug/confirmation" element={<ApplicationConfirmation/>}/><Route path="/application-success/:reference" element={<ApplicationConfirmation/>}/><Route path="/saved-jobs" element={<SavedJobs/>}/><Route path="/track-application" element={<TrackApplication/>}/><Route path="/legal/:type" element={<LegalPage/>}/><Route path="/account" element={<Account/>}/><Route path="/account/login" element={<CandidateLogin/>}/><Route path="/account/register" element={<Register/>}/><Route path="/account/forgot-password" element={<ForgotPassword/>}/><Route path="/account/reset-password" element={<ResetPassword/>}/><Route path="/auth/login" element={<Login/>}/><Route path="/admin/login" element={<Login adminOnly/>}/><Route path="/auth/forgot-password" element={<ForgotPassword/>}/><Route path="/auth/reset-password" element={<ResetPassword/>}/><Route path="/unauthorized" element={<Unauthorized/>}/><Route path="/candidate/dashboard" element={<ProtectedRoute roles={[ROLES.CANDIDATE]}><CandidateDashboard/></ProtectedRoute>}/>
  <Route path="/admin" element={<ProtectedRoute roles={STAFF_ROLES}><AdminLayout/></ProtectedRoute>}><Route index element={<AdminDashboard/>}/><Route path="jobs" element={<AdminJobs/>}/><Route path="jobs/new" element={<ProtectedRoute roles={[ROLES.ADMIN,ROLES.SUPER_ADMIN]}><JobEditor/></ProtectedRoute>}/><Route path="jobs/:id/edit" element={<ProtectedRoute roles={[ROLES.ADMIN,ROLES.SUPER_ADMIN]}><JobEditor/></ProtectedRoute>}/><Route path="applications" element={<AdminApplications/>}/><Route path="applications/:id" element={<ApplicationReview/>}/><Route path="candidates" element={<AdminCandidates/>}/><Route path="candidates/:id" element={<CandidateProfilePage/>}/><Route path="interviews" element={<AdminInterviews/>}/><Route path="reports" element={<ProtectedRoute roles={[ROLES.VIEWER,ROLES.ADMIN,ROLES.SUPER_ADMIN]}><AdminReports/></ProtectedRoute>}/><Route path="users" element={<ProtectedRoute roles={[ROLES.SUPER_ADMIN]}><AdminUsers/></ProtectedRoute>}/><Route path="settings" element={<ProtectedRoute roles={[ROLES.SUPER_ADMIN]}><AdminSettings/></ProtectedRoute>}/></Route>
  <Route path="/hire" element={<Hire/>}/><Route path="/facilities" element={<Facilities/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/>
</Routes></Suspense></main>{!admin&&<Footer/>}{!admin&&<a href="https://whatsapp.com/channel/0029VaRHlCdDDmFOW66gnK1I" className="floating whatsapp" target="_blank" rel="noreferrer" aria-label="Join our WhatsApp channel">☏<span>WhatsApp</span></a>}</div>}
export default function App(){return <BrowserRouter><AuthProvider><AppLayout/></AuthProvider></BrowserRouter>}
