-- Full ATS extension. Apply after 001_recruitment_portal.sql and
-- 002_enum_extensions.sql.

alter table public.jobs add column if not exists city text,add column if not exists trade text,add column if not exists employer_name text,add column if not exists employer_confidential boolean not null default true,add column if not exists permission_number text,add column if not exists salary_display text,add column if not exists experience_min numeric,add column if not exists experience_max numeric,add column if not exists experience_text text,add column if not exists qualification text,add column if not exists description text,add column if not exists requirements jsonb not null default '[]',add column if not exists responsibilities jsonb not null default '[]',add column if not exists benefits jsonb not null default '[]',add column if not exists contract_type text,add column if not exists contract_duration text,add column if not exists working_hours text,add column if not exists overtime_available boolean not null default false,add column if not exists interview_date timestamptz,add column if not exists interview_location text,add column if not exists application_deadline date,add column if not exists closing_date date,add column if not exists urgent boolean not null default false,add column if not exists poster_url text,add column if not exists published_at timestamptz;

create table if not exists public.job_campaigns(id uuid primary key default gen_random_uuid(),source_key text unique,title text not null,permission_number text,poster_url text,status text not null default 'Draft',interview_date timestamptz,interview_location text,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.jobs add column if not exists campaign_id uuid references public.job_campaigns(id) on delete set null;

create table if not exists public.candidates(id uuid primary key default gen_random_uuid(),user_id uuid unique references public.profiles(id) on delete set null,full_name text not null,father_name text,cnic text,date_of_birth date,gender text,nationality text not null default 'Pakistani',phone text,whatsapp text,email text,city text,province text,current_address text,permanent_address text,passport_number text,passport_issue_date date,passport_expiry_date date,passport_status text,country_of_issue text,highest_qualification text,technical_qualification text,current_trade text,total_experience numeric,gulf_experience numeric,saudi_experience numeric,certifications text[],languages text[],driving_license text,saudi_driving_license text,expected_salary text,current_salary text,availability text,preferred_country text,profile_status text not null default 'Active',duplicate_flags jsonb not null default '[]',consent_at timestamptz,retention_until date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.applications add column if not exists candidate_record_id uuid references public.candidates(id) on delete restrict,add column if not exists source text not null default 'Website',add column if not exists recruiter_id uuid references public.profiles(id),add column if not exists rating smallint check(rating between 1 and 5),add column if not exists submitted_at timestamptz not null default now();

create table if not exists public.candidate_notes(id uuid primary key default gen_random_uuid(),candidate_id uuid not null references public.candidates(id) on delete cascade,application_id uuid references public.applications(id) on delete cascade,note text not null,is_private boolean not null default true,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table if not exists public.interviews(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.applications(id) on delete cascade,scheduled_at timestamptz not null,location text,maps_url text,interviewer text,instructions text,status text not null default 'Scheduled',result text,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),application_id uuid references public.applications(id) on delete cascade,candidate_id uuid references public.candidates(id) on delete cascade,channel text not null check(channel in('email','whatsapp','sms','in_app')),template_key text not null,recipient text not null,status text not null default 'Queued',provider_id text,error text,payload jsonb not null default '{}',created_at timestamptz not null default now(),sent_at timestamptz);
create table if not exists public.email_logs(id uuid primary key default gen_random_uuid(),notification_id uuid references public.notifications(id) on delete set null,provider text,recipient text not null,subject text,status text not null,response jsonb,created_at timestamptz not null default now());
create table if not exists public.whatsapp_logs(id uuid primary key default gen_random_uuid(),notification_id uuid references public.notifications(id) on delete set null,provider text,recipient text not null,template_name text,status text not null,response jsonb,created_at timestamptz not null default now());
create table if not exists public.audit_logs(id bigint generated always as identity primary key,user_id uuid references public.profiles(id),action text not null,table_name text not null,record_id text,old_value jsonb,new_value jsonb,ip_address inet,created_at timestamptz not null default now());
create table if not exists public.tags(id uuid primary key default gen_random_uuid(),name text unique not null,color text not null default '#061b33');
create table if not exists public.candidate_tags(candidate_id uuid references public.candidates(id) on delete cascade,tag_id uuid references public.tags(id) on delete cascade,primary key(candidate_id,tag_id));
create table if not exists public.application_tags(application_id uuid references public.applications(id) on delete cascade,tag_id uuid references public.tags(id) on delete cascade,primary key(application_id,tag_id));
create table if not exists public.regional_offices(id uuid primary key default gen_random_uuid(),name text not null,address text,phone text,email text,is_head_office boolean not null default false,active boolean not null default true);
create table if not exists public.settings(key text primary key,value jsonb not null default '{}',updated_by uuid references public.profiles(id),updated_at timestamptz not null default now());

create index if not exists jobs_slug_idx on public.jobs(slug);create index if not exists jobs_status_created_idx on public.jobs(status,created_at desc);create index if not exists jobs_trade_idx on public.jobs(trade);create index if not exists candidates_cnic_idx on public.candidates(cnic);create index if not exists candidates_passport_idx on public.candidates(passport_number);create index if not exists candidates_email_idx on public.candidates(lower(email));create index if not exists candidates_phone_idx on public.candidates(phone);create index if not exists candidates_trade_city_idx on public.candidates(current_trade,city);create index if not exists candidates_created_idx on public.candidates(created_at desc);create index if not exists applications_reference_idx on public.applications(reference_number);create index if not exists applications_status_created_idx on public.applications(status,created_at desc);create index if not exists applications_job_idx on public.applications(job_id);create index if not exists applications_recruiter_idx on public.applications(recruiter_id);create index if not exists interviews_schedule_idx on public.interviews(scheduled_at);

create sequence if not exists public.application_reference_seq;
create or replace function public.next_application_reference() returns text language sql security definer set search_path=public as $$select 'TA-'||extract(year from now())::text||'-'||lpad(nextval('public.application_reference_seq')::text,6,'0')$$;
create or replace function public.find_candidate_duplicates(p_cnic text,p_passport text,p_email text,p_phone text,p_whatsapp text,p_name text,p_dob date) returns table(id uuid,matched_on text[]) language sql stable security definer set search_path=public as $$select c.id,array_remove(array[case when nullif(p_cnic,'') is not null and c.cnic=p_cnic then 'CNIC' end,case when nullif(p_passport,'') is not null and c.passport_number=p_passport then 'Passport' end,case when nullif(p_email,'') is not null and lower(c.email)=lower(p_email) then 'Email' end,case when nullif(p_phone,'') is not null and c.phone=p_phone then 'Phone' end,case when nullif(p_whatsapp,'') is not null and c.whatsapp=p_whatsapp then 'WhatsApp' end,case when lower(c.full_name)=lower(p_name) and c.date_of_birth=p_dob then 'Name + DOB' end],null) from public.candidates c where (nullif(p_cnic,'') is not null and c.cnic=p_cnic) or (nullif(p_passport,'') is not null and c.passport_number=p_passport) or (nullif(p_email,'') is not null and lower(c.email)=lower(p_email)) or (nullif(p_phone,'') is not null and c.phone=p_phone) or (nullif(p_whatsapp,'') is not null and c.whatsapp=p_whatsapp) or (lower(c.full_name)=lower(p_name) and c.date_of_birth=p_dob)$$;
create or replace function public.track_application(p_reference text,p_identifier text) returns table(job_title text,submitted_at timestamptz,status public.application_status,next_action text,interview_date timestamptz,missing_documents text[]) language sql security definer set search_path=public as $$select a.job_title,a.submitted_at,a.status,case when a.status='Submitted' then 'Your application is awaiting review.' when a.status='Interview Scheduled' then 'Attend the scheduled interview with original documents.' when a.status='Documents Pending' then 'Contact recruitment to provide missing documents.' else 'The recruitment team will contact you when action is required.' end,a.interview_date,array[]::text[] from public.applications a join public.candidates c on c.id=a.candidate_record_id where upper(a.reference_number)=upper(p_reference) and (c.cnic=p_identifier or c.phone=p_identifier or c.whatsapp=p_identifier) limit 1$$;

create or replace function public.audit_row_change() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.audit_logs(user_id,action,table_name,record_id,old_value,new_value) values(auth.uid(),tg_op,tg_table_name,coalesce(new.id,old.id)::text,to_jsonb(old),to_jsonb(new));return coalesce(new,old);end;$$;
create trigger audit_jobs after insert or update or delete on public.jobs for each row execute function public.audit_row_change();create trigger audit_applications after insert or update or delete on public.applications for each row execute function public.audit_row_change();create trigger audit_candidates after insert or update or delete on public.candidates for each row execute function public.audit_row_change();

create or replace function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role in('recruiter','admin','super_admin','viewer'))$$;
create or replace function public.can_write_recruitment() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role in('recruiter','admin','super_admin'))$$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role in('admin','super_admin'))$$;

drop policy if exists "staff manage jobs" on public.jobs;create policy "writers manage jobs" on public.jobs for all using(public.can_write_recruitment()) with check(public.can_write_recruitment());
drop policy if exists "staff update applications" on public.applications;create policy "writers update applications" on public.applications for update using(public.can_write_recruitment()) with check(public.can_write_recruitment());
create policy "admins manage profiles" on public.profiles for update using(public.is_admin()) with check(public.is_admin());

do $$declare t text;begin foreach t in array array['job_campaigns','candidates','candidate_notes','interviews','notifications','email_logs','whatsapp_logs','audit_logs','tags','candidate_tags','application_tags','regional_offices','settings'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy "staff read candidates" on public.candidates for select using(public.is_staff() or user_id=auth.uid());create policy "candidate create own profile" on public.candidates for insert with check(user_id=auth.uid());create policy "candidate update own profile" on public.candidates for update using(user_id=auth.uid()) with check(user_id=auth.uid());create policy "writers manage candidates" on public.candidates for all using(public.can_write_recruitment()) with check(public.can_write_recruitment());
create policy "staff manage campaigns" on public.job_campaigns for all using(public.can_write_recruitment()) with check(public.can_write_recruitment());create policy "staff read campaigns" on public.job_campaigns for select using(public.is_staff());
create policy "staff notes" on public.candidate_notes for all using(public.can_write_recruitment()) with check(public.can_write_recruitment());create policy "staff interviews" on public.interviews for all using(public.can_write_recruitment()) with check(public.can_write_recruitment());create policy "candidate reads interviews" on public.interviews for select using(exists(select 1 from public.applications a where a.id=application_id and a.candidate_id=auth.uid()));
create policy "staff notifications" on public.notifications for select using(public.is_staff());create policy "staff email logs" on public.email_logs for select using(public.is_admin());create policy "staff whatsapp logs" on public.whatsapp_logs for select using(public.is_admin());create policy "admins audit logs" on public.audit_logs for select using(public.is_admin());create policy "staff tags" on public.tags for all using(public.can_write_recruitment()) with check(public.can_write_recruitment());create policy "staff candidate tags" on public.candidate_tags for all using(public.can_write_recruitment()) with check(public.can_write_recruitment());create policy "staff application tags" on public.application_tags for all using(public.can_write_recruitment()) with check(public.can_write_recruitment());create policy "public offices" on public.regional_offices for select using(active);create policy "admin offices" on public.regional_offices for all using(public.is_admin()) with check(public.is_admin());create policy "admin settings" on public.settings for all using(public.is_admin()) with check(public.is_admin());
grant execute on function public.track_application(text,text) to anon,authenticated;grant execute on function public.next_application_reference() to authenticated;grant execute on function public.find_candidate_duplicates(text,text,text,text,text,text,date) to authenticated;
update storage.buckets set file_size_limit=5242880,allowed_mime_types=array['application/pdf','image/jpeg','image/png','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'] where id='candidate-documents';
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('job-posters','job-posters',true,10485760,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "public reads job posters" on storage.objects for select using(bucket_id='job-posters');create policy "staff uploads job posters" on storage.objects for insert to authenticated with check(bucket_id='job-posters' and public.can_write_recruitment());create policy "staff updates job posters" on storage.objects for update to authenticated using(bucket_id='job-posters' and public.can_write_recruitment());

create or replace function public.queue_application_notifications() returns trigger language plpgsql security definer set search_path=public as $$declare c public.candidates%rowtype;begin select * into c from public.candidates where id=new.candidate_record_id;if tg_op='INSERT' then if c.email is not null then insert into public.notifications(application_id,candidate_id,channel,template_key,recipient,payload) values(new.id,c.id,'email','application_received',c.email,jsonb_build_object('name',c.full_name,'jobTitle',new.job_title,'reference',new.reference_number));end if;if c.whatsapp is not null then insert into public.notifications(application_id,candidate_id,channel,template_key,recipient,payload) values(new.id,c.id,'whatsapp','application_received',c.whatsapp,jsonb_build_object('template','application_received','parameters',jsonb_build_array(c.full_name,new.job_title,new.reference_number)));end if;elsif old.status is distinct from new.status then if c.email is not null then insert into public.notifications(application_id,candidate_id,channel,template_key,recipient,payload) values(new.id,c.id,'email','status_update',c.email,jsonb_build_object('name',c.full_name,'jobTitle',new.job_title,'reference',new.reference_number,'status',new.status));end if;if c.whatsapp is not null then insert into public.notifications(application_id,candidate_id,channel,template_key,recipient,payload) values(new.id,c.id,'whatsapp','status_update',c.whatsapp,jsonb_build_object('template','application_status_update','parameters',jsonb_build_array(c.full_name,new.job_title,new.reference_number,new.status)));end if;end if;return new;end;$$;
create trigger queue_application_notifications after insert or update of status on public.applications for each row execute function public.queue_application_notifications();
create or replace function public.queue_interview_notification() returns trigger language plpgsql security definer set search_path=public as $$declare a public.applications%rowtype;c public.candidates%rowtype;begin select * into a from public.applications where id=new.application_id;select * into c from public.candidates where id=a.candidate_record_id;if c.email is not null then insert into public.notifications(application_id,candidate_id,channel,template_key,recipient,payload) values(a.id,c.id,'email','interview_scheduled',c.email,jsonb_build_object('name',c.full_name,'jobTitle',a.job_title,'reference',a.reference_number,'date',new.scheduled_at,'location',new.location,'instructions',new.instructions));end if;if c.whatsapp is not null then insert into public.notifications(application_id,candidate_id,channel,template_key,recipient,payload) values(a.id,c.id,'whatsapp','interview_scheduled',c.whatsapp,jsonb_build_object('template','interview_scheduled','parameters',jsonb_build_array(c.full_name,a.job_title,a.reference_number,new.scheduled_at,new.location)));end if;return new;end;$$;
create trigger queue_interview_notification after insert on public.interviews for each row execute function public.queue_interview_notification();
create or replace function public.record_application_status() returns trigger language plpgsql security definer set search_path=public as $$begin if old.status is distinct from new.status then insert into public.application_status_history(application_id,status,note,changed_by) values(new.id,new.status,'Status updated',auth.uid());end if;return new;end;$$;
create trigger record_application_status after update of status on public.applications for each row execute function public.record_application_status();
